### ISSUE TITLE
geant4 example, create the directory to write the example

### ISSUE THREAD

**Issue by RoyBellingan** [niess/pumas#17]
In case the file is compiled not following the standard method the line gdml.Write("examples/data/geometry.gdml", worldPhysical);	
will fail with a non super easy to understand error (IOException instead of sayng can not write the file, please create the folder yourself)

Is possible to add those two lines to create the folder ?
The header #include <filesystem>

 the command
std::filesystem::create_directories("examples/data");

**Comment by RoyBellingan** [comment]
Thank you very much ! And well of course if it works is fine!

**Comment by niess** [comment]
:)
