### ISSUE TITLE
'make tabulate' in Makefile and docs

### ISSUE THREAD

**Issue by 1313e** [niess/pumas#3]
This is just something simple, but requires changes regardless.
In the [installation docs](https://github.com/niess/pumas/wiki/Installation#using-make-on-unix), it mentions that PUMAS can be installed with `make && make tabulate`.
However, `make tabulate` has not been a thing anymore since 5a66cee as the tabulation functions are now contained within PUMAS itself.
It is still however mentioned in the docs (and in the Makefile as well as a valid action that has no effect), which can cause some confusion.

**Comment by niess** [comment]
Hello Ellert  :)

Indeed. Thanks! I removed it in the Makefile but only in the dev branch for now. The wiki doc was updated.
